# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'graphql-client', '~> 0.15.0'

group :development do
  gem "pry", group: :development
end
